on: [push, pull_request]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc:  ['8.0.2','8.2.2','8.6.5', '8.8.3','8.10.2','latest']
        cabal: ['1.24.0.0']

        os: [ubuntu-latest, macOS-latest, windows-latest]

        include:
      # for the matrix leg matching the os and version
          - os: windows-latest
            ghc: latest
            cabal: latest
          - os: macOS-latest
            ghc: latest
            cabal: latest
          - os: ubuntu-latest
            ghc: latest
            cabal: latest
    name: Haskell GHC ${{ matrix.ghc }} and cabal ${{matrix.cabal}} on ${{matrix.os}}
    env:
      CONFIG: "--enable-tests"

    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1.3 # the .3 is a bug fix?
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal update
      - run: cabal clean
      - run: cabal configure $CONFIG
      - run: cabal freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle


          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          # restore keys is a fall back when the freeze plan is different
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal build
      - run: cabal test
      - run: cabal bench
      - run: cabal sdist -o `pwd`
      - run: cabal check
      - run: cabal v1-install ralist*.tar.gz